### ISSUE TITLE
How to submit?

### ISSUE THREAD

**Issue by gangweix** [hermannsblum/fishyscapes#15]
I read carefully what you said about the submit process, but I still don't know how to commit my pytorch code?

**Comment by gangweix** [comment]
What this submited *.zip should contain? And I don't want to expose my original source code.

**Comment by hermannsblum** [comment]
Thanks for your question! You don't have to publicly expose your code.
All you need to include in the PR is a function that can run your method, e.g. by loading a model binary (like tensorflow or onnx), or by importing a function from a custom pytorch code. You can submit all model weigths, binaries, and code as part of the zip file in the submission form.

Please also add detailed instructions how to install and run your method then.
