### ISSUE TITLE
Are you considering to change the submit procedure into results uploading in the future ?

### ISSUE THREAD

**Issue by lyxok1** [hermannsblum/fishyscapes#20]
Hi, the current evaluation procedure seems a bit cumbersome, the evaluation side should care about the running environment of uploaded detector, on the other hand, users of the benchmark have to writing additional code and instructions. 

I wonder are you considering to change the evaluation procedure into the form of results uploading like most of other challenges does ? e.g. you can provide download link of test image for different subset (LAF, static, web etc.), users only need to predict a result file for each image (e.g. ${image name}.npy matrix) and upload them as a .zip, instead of uploading the model. In the evaluation side, you can directly evaluate the results regardless of running evironment of anomaly detectors.

I think this change will help to promote this benchmark to broader usage. Thanks~

**Comment by hermannsblum** [comment]
I appreciate the suggestion, but it is unfortunately not compatible with our FS Web methodology, where methods are evaluated on data that is only generated after they are submitted.

The submission is actually very eqsy for tensorflow, where you just save and upload your computation graph.

For pytorch and others, we were always hoping to get money and hire an assistant to set up something where people can upload docker images that just run on all images in a mounted directory, but we never got funding for that. If you would like to volunteer you are very welcome 😉

**Comment by hermannsblum** [comment]
fyi we now have a new submission system. Still no uploading of result images, but easier debugging for people who submit.
