### ISSUE TITLE
about submit

### ISSUE THREAD

**Issue by chensongloose** [hermannsblum/fishyscapes#27]
Thank you for your work on fishyscapes benchmark!
It seems that the link to submit the model on the official website cannot be [opened.](https://fishyscapes.com/submission)

**Comment by hermannsblum** [comment]
I just tested it, it still works for me. It is a link to a google form. Could you check via an alternative internet connection? Maybe google is blocked from where you tried.

**Comment by hermannsblum** [comment]
If you still have troubles submitting you can always send me an email and we figure out how to transfer the model and code for your specific submission.

**Comment by chensongloose** [comment]
Thanks for your great work with fishyscapes! I would like to know when I can submit my method to fishyscapes.
Looking forward to your reply!

**Comment by hermannsblum** [comment]
You can already prepare a model as described on the website. We should have the new system running by the end of the week.

**Comment by chensongloose** [comment]
It is mentioned in the official website that segmentation and anomaly scores are obtained through the singularity image.
Want to know what format and content the input is when singularity image is called?

**Comment by hermannsblum** [comment]
I just put out some additional info for the submission, I hope this already helps: https://fishyscapes.com/submission

**Comment by hermannsblum** [comment]
The new submission system is now live.

**Comment by chensongloose** [comment]
> The new submission system is now live.

Hello! My .simg file size is 11.4GB out of limit. Is there any other way to submit .simg file

**Comment by hermannsblum** [comment]
10gb is the absolute maximum that google allows, I cannot set a higher upload size. The best way to reduce your container size is to use a smaller base image (eg start with just an nvidia cuda image) and only install the dependencies you need to run inference, not training.

**Comment by chensongloose** [comment]
After I filled out the form and clicked the Submit button, something went wrong and please try again. After I tried several times, the problem is still the same. How can I solve it?
The singularity container files are in .simg format and are less than 10gb.
Looking forward to your reply!

**Comment by hermannsblum** [comment]
I just tried it and it worked. Hard to say what is going on, because google does not report any error to me.
Can you try uploading a smaller file, just to check whether file size is the problem?
If it still does not work you can upload the file somewhere else you can send me a link via email and I upload it for you, but ideally google form submission really should work for everyone.

**Comment by chensongloose** [comment]
I tried a new upload and only uploaded one image. My guess is that the singularity container file was too large and failed to submit.

**Comment by chensongloose** [comment]
> 
I have uploaded the singularity container file to onedrive, which is available at (https://1drv.ms/u/s!AoWLyWRHB4jwgQcxBNtbSQ11ZA22?e=TTr8yk) or download it from googledrive (https://drive.google.com/file/d/1bgX5KZNPTx_MsQh4fa-RAwj22H_yDqYm/view?usp=sharing) .
Thanks for you help!

**Comment by hermannsblum** [comment]
Just to debug the error, did you try a smaller file?
Did you upload the file or just select from your gdrive?

**Comment by chensongloose** [comment]
In order to debug the error, I selected a smaller file upload from gdrive, and the submission was successful.



---- Replied Message ----
| From | ***@***.***> |
| Date | 02/16/2023 22:28 |
| To | ***@***.***> |
| Cc | ***@***.***>、State ***@***.***> |
| Subject | Re: [hermannsblum/fishyscapes] about submit (Issue #27) |

Just to debug the error, did you try a smaller file?
Did you upload the file or just select from your gdrive?
