### ISSUE TITLE
Couldn't  create a submission container

### ISSUE THREAD

**Issue by WenjieZhao1** [hermannsblum/fishyscapes#68]
Hi. Thank you for maintianing such a benchmark for Anomaly detection. Recently I want to submit my method, but I found it couldn't be created correctly when I try about the example https://github.com/4PiR2/fishyscapes_simg_example. Could you please reproduce it since I can't run it? Besides, could you please give me any guide about how to create that container for my method.

**Comment by hermannsblum** [comment]
sorry, without specific info I cannot help you. What did not work about the example container? 
Did you manage to install docker? Can you create a docker container for your method and run your method with that container? Can you convert that container to singularity/apptainer?

**Comment by WenjieZhao1** [comment]
I just follow the example repo and try to create a docker for synboost.
When I try to execute the first comand to create container, it will get
error message.

**Comment by hermannsblum** [comment]
If you don't even share the error message I really cannot help you.
